// Code generated by tygo. DO NOT EDIT.
import type { Bounds, Config, Result, Strategy } from "./engine";

//////////
// source: api.go
/*
Package api exposes the engine over HTTP as a small JSON API. It stays
thin on purpose: decode, run the engine, encode. All validation lives in
the engine; the API only translates errors into status codes.
*/

/**
 * DefaultConfigResponse is the body of GET /api/config/default: the
 * default world plus the engine's field bounds, so the frontend drives
 * its controls and clamping from the same numbers the engine enforces.
 */
export interface DefaultConfigResponse {
  config: Config;
  bounds: Bounds;
}
/**
 * ComparisonResponse bundles what the dashboard needs to render one
 * comparison: the config that was run, echoed back so frontend state stays
 * honest, and one result per strategy.
 */
export interface ComparisonResponse {
  config: Config;
  results: Result[];
}
/**
 * ScenarioRequest is the body of POST /api/scenario: one panel's effective
 * config plus its strategy.
 */
export interface ScenarioRequest {
  config: Config;
  strategy: Strategy;
}
/**
 * ScenarioResponse carries everything one dashboard panel needs: the
 * echoed config, the cascade result, and the network topology as
 * [from, to] node-index pairs (deterministic from the config's graph
 * fields) for the frontend's force layout.
 */
export interface ScenarioResponse {
  config: Config;
  result: Result;
  edges: number /* int */[][];
}
