// Code generated by tygo. DO NOT EDIT.
import type { Config, Result } from "./engine";

//////////
// source: api.go
/*
Package api exposes the engine over HTTP as a small JSON API. It stays
thin on purpose: decode, run the engine, encode. All validation lives in
the engine; the API only translates errors into status codes.
*/

/**
 * ComparisonResponse bundles what the dashboard needs to render one
 * comparison: the config that was run, echoed back so frontend state stays
 * honest, and one result per strategy.
 */
export interface ComparisonResponse {
  config: Config;
  results: Result[];
}
