// Code generated by tygo. DO NOT EDIT.

//////////
// source: scenario.go

/**
 * Strategy selects who gets educated.
 */
export type Strategy = string;
export const StrategyNone: Strategy = "none";
export const StrategyRandom: Strategy = "random";
export const StrategyMostConnected: Strategy = "most-connected";
/**
 * Config fully describes one simulation world. It is the single source of
 * truth for parameters: API and frontend types will be generated from the
 * structs in this file, never redefined by hand. Identical configs produce
 * identical results; all randomness flows from the three seeds.
 */
export interface Config {
  numStudents: number /* int */;
  edgesPerNode: number /* int */; // attachment edges per new student (network density)
  triangleProb: number /* float64 */; // chance to close a friend-of-a-friend triangle
  forwardProb: number /* float64 */; // chance a student forwards the fake along an edge
  numEducated: number /* int */; // students the education program reaches
  origin: number /* int */; // student who first posts the fake
  graphSeed: number /* uint64 */;
  thresholdSeed: number /* uint64 */;
  educationSeed: number /* uint64 */; // used by the random strategy only
}
/**
 * Result is the outcome of one scenario run.
 */
export interface Result {
  strategy: Strategy;
  educated: number /* int */[];
  reachedAtRound: number /* int */[]; // per node; -1 means never reached
  numReached: number /* int */;
  numRounds: number /* int */;
  reachedPct: number /* float64 */;
}
