// Code generated by tygo. DO NOT EDIT.

//////////
// source: scenario.go

/**
 * Strategy selects who gets educated.
 */
export type Strategy = string;
export const StrategyNone: Strategy = "none";
export const StrategyRandom: Strategy = "random";
export const StrategyMostConnected: Strategy = "most-connected";
/**
 * Config fully describes one simulation world. It is the single source of
 * truth for parameters: API and frontend types will be generated from the
 * structs in this file, never redefined by hand. Identical configs produce
 * identical results; all randomness flows from the three seeds.
 */
export interface Config {
  numStudents: number /* int */;
  edgesPerNode: number /* int */; // attachment edges per new student (network density)
  triangleProb: number /* float64 */; // chance to close a friend-of-a-friend triangle
  /**
   * Forwarding is an additive composite (see ForwardChance): a baseline
   * propensity, raised by how novel/shocking the fake is, lowered by the
   * year group's ambient harm awareness.
   */
  forwardProb: number /* float64 */; // baseline chance a student forwards the fake along an edge
  novelty: number /* float64 */; // how novel/shocking the fake is (0..1); raises forwarding
  harmAwareness: number /* float64 */; // ambient AI-literacy / harm awareness in the year group (0..1); lowers forwarding
  numEducated: number /* int */; // students the education program reaches
  programEffect: number /* float64 */; // how strongly the program suppresses an educated student's forwarding (0..1; 1 = never forwards)
  origin: number /* int */; // student who first posts the fake
  graphSeed: number /* uint64 */;
  thresholdSeed: number /* uint64 */;
  educationSeed: number /* uint64 */; // used by the random strategy only
}
/**
 * IntBounds is an inclusive allowed range for an integer Config field.
 */
export interface IntBounds {
  min: number /* int */;
  max: number /* int */;
}
/**
 * FloatBounds is an inclusive allowed range for a float Config field.
 */
export interface FloatBounds {
  min: number /* float64 */;
  max: number /* float64 */;
}
/**
 * Bounds gives the allowed range for every absolute Config field. These
 * are realism limits, not mathematical ones: a student does not keep 150
 * close friendships, and a guaranteed forward is not a plausible base
 * rate. numEducated and origin are relational (0..numStudents and
 * 0..numStudents-1) and therefore not listed; seeds are unrestricted.
 */
export interface Bounds {
  numStudents: IntBounds;
  edgesPerNode: IntBounds;
  triangleProb: FloatBounds;
  forwardProb: FloatBounds;
  novelty: FloatBounds;
  harmAwareness: FloatBounds;
  programEffect: FloatBounds;
}
/**
 * Result is the outcome of one scenario run.
 */
export interface Result {
  strategy: Strategy;
  educated: number /* int */[];
  reachedAtRound: number /* int */[]; // per node; -1 means never reached
  numReached: number /* int */;
  numRounds: number /* int */;
  reachedPct: number /* float64 */;
}
